name: 'Yarn install'
description: 'Runs setup node + cache + yarn install'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      id: setup-node
      with:
        node-version-file: 'package.json'
        check-latest: true
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/yarn.lock', 'patches/*.patch') }}
    - name: Install Yarn dependencies
      run: |
        # Deals with yarn (v1) install flakiness
        yarn || yarn --network-concurrency 1
        # Another install flakiness fix (at least in yarn v1 with node 20)
        # yarn postinstall isn't always run (?!) so we run it manually
        yarn postinstall
      shell: bash
    - name: Fail if someone forgot to commit "yarn.lock"
      run: git diff --exit-code
      shell: bash
